((topmost-intro <0,0>))
((class-open <1,0>))
((inclass <1,0>) (access-label <1,0>))
((inclass <2,0>) (topmost-intro <2,0>))
((class-close <4,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((namespace-open <1,0>))
((innamespace <1,0>) (topmost-intro <1,0>))
((member-init-intro <1,4>))
((defun-open <2,4>))
((defun-close <1,4>))
((namespace-close <6,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((class-close <2,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((inher-intro <1,0>))
((class-open <2,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((member-init-intro <1,4>))
((member-init-cont <1,10>))
((inclass <4,0>) (inline-open))
((inline-close <1,4>))
((inclass <6,0>) (topmost-intro <1,0>))
((member-init-intro <1,4>))
((member-init-cont <1,10>))
((inclass <9,0>) (inline-open))
((inline-close <1,4>))
((class-close <13,0>))
