((topmost-intro <0,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((defun-block-intro <1,4>))
((statement <1,8>))
((statement-block-intro <1,8>))
((block-close <2,8>))
((inline-close <5,4>))
((class-close <7,0>))
