((topmost-intro <0,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>) (cpp-macro))
((cpp-define-intro <1,0>))
((statement <1,4>))
((defun-block-intro <4,0>) (cpp-macro))
((cpp-define-intro <1,0>))
((statement-cont <1,4>))
((statement <2,4>))
((defun-block-intro <8,0>) (cpp-macro))
((cpp-define-intro <1,0>))
((statement-cont <1,4>))
((defun-close <11,0>))
